### ISSUE TITLE
application/octet-stream on localhost

### ISSUE THREAD

**Issue by mnlfischer** [http-party/http-server#173]
getting a "download" file when trying to visit localhost (index.html) in chrome 44.0.2403.157 m on windows 7.

console output:
[Tue, 25 Aug 2015 09:01:57 GMT] "GET /" "Mozilla/5.0 (Windows NT 6.1; WOW64) App
leWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"

File Typ: application/octet-stream

Not sure if that issue caused by http-server or browser. Tested it in firefox  esr 38.0.1 with the same issue.

**Comment by mnlfischer** [comment]
fixed this problem by reinstall chrome. Issue can be closed.

**Comment by JelloRanger** [comment]
Getting this same exact problem. Using Chrome 44.0.2403.157 and Windows 7 as well.

**Comment by Slapbox** [comment]
Getting this same problem in Chrome and in Firefox. on Windows 7. Not in Internet Explorer, but instead nothing loads.

**Comment by joelcdoyle** [comment]
Can confirm this issue is still present in Chrome 55.0.2883.87 on Windows 7.

**Comment by stevengiraldo** [comment]
I have the same problem with last Chrome version 64

**Comment by BigBlueHat** [comment]
Can you all test in curl to verify the headers you're seeing?

```
$ curl -v http://localhost:8080/index.html
```

Thanks!

**Comment by thornjad** [comment]
I'm closing this for now since there has been no further mention or +1's of this issue. Anyone who is still seeing this issue, please test with the latest version of http-server, and if it still shows up, please reopen this issue with the output of the `curl` command above!

**Comment by JoBoDo** [comment]
I'm getting this issue with the latest version of Firefox. It didn't happen in IE.
```
G:\d2h_repos
λ curl -v localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< server: ecstatic-3.3.2
< cache-control: no-cache, no-store, must-revalidate
< last-modified: Thu, 16 Jan 2020 17:53:42 GMT
< etag: W/"1407374885549513-1433-2020-01-16T17:53:42.497Z"
< content-length: 1433
< content-type: application/octet-stream; charset=utf-8
< Date: Thu, 16 Jan 2020 17:58:39 GMT
< Connection: keep-alive
<
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html">
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.15.1/dist/phaser-arcade-physics.min.js"></script>
</head>
```
